/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Shared government CSS-variable tokens
        canvas: 'var(--color-canvas, #090d16)',
        border: 'var(--color-border, rgba(255,255,255,0.1))',
        'border-strong': 'var(--color-border-strong, rgba(255,255,255,0.2))',
        hover: 'var(--color-hover, rgba(255,255,255,0.05))',
        fg: {
          DEFAULT: 'var(--color-fg, #f9fafb)',
          muted: 'var(--color-fg-muted, #9ca3af)',
          subtle: 'var(--color-fg-subtle, #6b7280)',
          inverted: 'var(--color-fg-inverted, #111827)',
        },

        // User / Citizen portal palette
        "background": "#F5F7FA",
        "on-background": "#0d1c2e",
        "surface": "#F8FAFC",
        "on-surface": "#0d1c2e",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F1F5F9",
        "surface-container": "#E8EDF4",
        "surface-container-high": "#DDE5EF",
        "surface-container-highest": "#D2DCE9",
        "surface-bright": "#F8FAFC",
        "surface-dim": "#CBD5E1",
        "surface-variant": "#D5DFEC",
        "on-surface-variant": "#44474e",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#74777f",
        "outline-variant": "#D9DEE7",
        "primary": "#0B2342",
        "on-primary": "#ffffff",
        "primary-container": "#102A4C",
        "on-primary-container": "#7a91b7",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#b0c8f1",
        "on-primary-fixed": "#001b3b",
        "secondary": "#A85B00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe932c",
        "on-secondary-container": "#8F4A00",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "tertiary": "#0B2342",
        "tertiary-container": "#17365D",
        "tertiary-fixed": "#dde1ff",
        "error": "#C62828",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#8C1616",
        "success": "#16803A",
        "success-container": "#DCFCE7",
        "info": "#2563A8",
        "info-container": "#DBEAFE",
        "warning": "#B66A00",
        "warning-container": "#FEF3C7",
      },
      fontFamily: {
        sans: ["Inter", "Plus Jakarta Sans", "system-ui", "sans-serif"],
        display: ["Cabinet Grotesk", "Outfit", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "display-hero": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 12px -2px rgba(15, 41, 74, 0.08), 0 2px 6px -1px rgba(15, 41, 74, 0.04)",
        pop: "0 8px 24px -4px rgba(15, 41, 74, 0.16), 0 4px 10px -2px rgba(15, 41, 74, 0.08)",
      },
    },
  },
  plugins: [],
};
